"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import Navbar from "./components/Navbar";
import dynamic from "next/dynamic";
import { usePathname } from "next/navigation";
import { AuthProvider, useAuth } from "./utils/AuthContext";
import { JSX } from "react";

const NoSSRSignUp = dynamic(() => import("./(auth)/signup/page"), { ssr: false });
const NoSSRSignIn = dynamic(() => import("./(auth)/signin/page"), { ssr: false });
const NoSSRProfile = dynamic(() => import("./(auth)/profile/page"), { ssr: false });
const NoSSRGetAstronauts = dynamic(() => import("./astronauts/page"), { ssr: false });
const NoSSRGetAstronaut = dynamic(() => import("./astronaut/page"), { ssr: false });
const NoSSRGetSuits = dynamic(() => import("./getsuits/page"), { ssr: false });
const NoSSRGetSuit = dynamic(() => import("./getsuit/page"), { ssr: false });
const NoSSRGetAttachements = dynamic(() => import("./attachments/page"), { ssr: false });
const NoSSRGetAttachment = dynamic(() => import("./attachment/page"), { ssr: false });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <AppContent />
        </AuthProvider>
      </body>
    </html>
  );
}

function AppContent() {
  const pathname = usePathname().replace(/\/$/, ""); // Get the current URL path
  console.log(pathname)
  const { isLoggedIn } = useAuth(); // Access the global auth state
  // Map routes to components dynamically
  const routeComponents: { [key: string]: JSX.Element } = {
    "/profile": isLoggedIn ? <NoSSRProfile /> : <NoSSRSignIn />,
    "/getsuits": isLoggedIn ? <NoSSRGetSuits /> : <NoSSRSignIn />,
    "/getsuit": isLoggedIn ? <NoSSRGetSuit /> : <NoSSRSignIn />,
    "/astronauts": isLoggedIn ? <NoSSRGetAstronauts /> : <NoSSRSignIn />,
    "/astronaut": isLoggedIn ? <NoSSRGetAstronaut /> : <NoSSRSignIn />,
    "/attachments": isLoggedIn ? <NoSSRGetAttachements /> : <NoSSRSignIn />,
    "/attachment": isLoggedIn ? <NoSSRGetAttachment /> : <NoSSRSignIn />,
    "/signup": <NoSSRSignUp />,
    "/signin": <NoSSRSignIn />,
  };

  // Determine the component to render based on the current pathname
  const renderComponent = routeComponents[pathname] || <NoSSRSignIn />;

  return (
    <>
      <Navbar setCurrentPage={() => {}} />
      <main>
        {renderComponent}
      </main>
    </>
  );
}