"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import Navbar from "./components/Navbar";
import { AuthProvider, useAuth } from "./utils/AuthContext";
import { JSX } from "react";

import GetProfile from "./auth/profile/page";
import GetSuits from "./getsuits/page";
import SignIn from "./auth/signin/page";
import GetSuit from "./getsuit/page";
import Astronauts from "./astronauts/page";
import Astronaut from "./astronaut/page";
import GetAttachment from "./attachment/page";
import Attachments from "./attachments/page";
import SignUp from "./auth/signup/page";
import Live from "./live/page";
import type { AppProps } from "next/app";
import { AstronautsProvider } from "./utils/astronautsProvider";
import ErrorBoundary from "./errorboundary/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  AppProps,
}: {
  children: React.ReactNode;
  AppProps: JSX.Element;
}) {
  return (
    <html lang="en">
      <head>{/* <link rel="icon" href="/favicon.ico" /> */}</head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ErrorBoundary>
          <AstronautsProvider>
            <AppContent {...AppProps} />
          </AstronautsProvider>
          </ErrorBoundary>
        </AuthProvider>
      </body>
    </html>
  );
}

function AppContent() {
  const pathname =
    typeof window !== "undefined"
      ? window.location.pathname.replace(/\/$/, "")
      : ""; // Client-side pathname
  const { isLoggedIn } = useAuth(); // Access the global auth state
  // Map routes to components dynamically
  const routeComponents: { [key: string]: JSX.Element } = {
    "/profile": isLoggedIn ? <GetProfile /> : <SignIn />,
    "/getsuits": isLoggedIn ? <GetSuits /> : <SignIn />,
    "/getsuit": isLoggedIn ? <GetSuit /> : <SignIn />,
    "/astronauts": isLoggedIn ? <Astronauts /> : <SignIn />,
    "/astronaut": isLoggedIn ? <Astronaut /> : <SignIn />,
    "/attachments": isLoggedIn ? <Attachments /> : <SignIn />,
    "/attachment": isLoggedIn ? <GetAttachment /> : <SignIn />,
    "/live": isLoggedIn ? <Live /> : <SignIn />,
    "/signup": <SignUp />,
    "/signin": <SignIn />,
  };

  // Determine the component to render based on the current pathname
  const renderComponent = routeComponents[pathname] || <SignIn />;

  return (
    <>
      <Navbar />
      <main>{renderComponent}</main>
    </>
  );
}
